
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module LabOne_TOP(
	input								CLOCK_50,
	inout 		[33:0]		GPIO0,
	input			[1:0]			GPIO0_IN 
);


//=======================================================
//  REG/WIRE declarations
//=======================================================
reg button0 = 0;
reg button1 = 0;


//=======================================================
//  Structural coding
//=======================================================

	//We are going to sample the button inputs on the rising edge 50Mhz system clock
	always@(posedge CLOCK_50)
		begin
			button0 <= GPIO0_IN[0];
			button1 <= GPIO0_IN[1];
		end

	Inverter InverterInstance(
		.a(button0),
		.q(GPIO0[0])
	);
	
	NandGate NandInstance(
		.a(button0),
		.b(button1),
		.q(GPIO0[1])
	);
	
	AndGate AndInstance(
		.a(button0),
		.b(button1),
		.q(GPIO0[2])
	);

	OrGate OrInstance(
		.a(button0),
		.b(button1),
		.q(GPIO0[3])
	);
endmodule