
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module CPE64LabThree_TOP(

	//////////// CLOCK //////////
	CLOCK_50,

	//////////// GPIO_0, GPIO_0 connect to GPIO Default //////////
	GPIO0,
	GPIO0_IN 
);

//=======================================================
//  PARAMETER declarations
//=======================================================


//=======================================================
//  PORT declarations
//=======================================================

//////////// CLOCK //////////
input 		          		CLOCK_50;

//////////// GPIO_0, GPIO_0 connect to GPIO Default //////////
inout 		    [33:0]		GPIO0;
input 		     [1:0]		GPIO0_IN;

//=======================================================
//  Structural coding
//=======================================================
Adder #(
		.constant(4'b0101)
	)AdderInstance(
		.UserNumber({GPIO0[1:0], GPIO0_IN[1:0]}),
		.sum(GPIO0[10:2])
);


endmodule
